version: '3.7'

services:
  main:
    container_name: main
    build:
      context: .
      target: production
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
      # - ${PORT}:${PORT}
      # - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - db

  db:
    image: mongo:4.4
    restart: always
    container_name: mongo-container
    networks:
      - backend
    ports:
      - 27017:27017

  # redis:
  #   container_name: redis
  #   image: redis:6
  #   networks:
  #     - backend

networks:
  backend:
